pool:
  vmImage: 'vs2017-win2016'
steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
- task: CredScan@2
  inputs:
    toolMajorVersion: 'V2'
- task: securedevelopmentteam.vss-secure-development-tools.build-task-semmle.Semmle@0
  displayName: 'Run Semmle (python)'
  inputs:
    language: python

